baseURL = 'https://zephyrtm.github.io/'
locale = 'en-us'
title = 'zephyrtm'
theme = 'risotto'

[[menu.main]]
name = "about"
url = "/about/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts/"
weight = 2

[params]
customCSS = ["css/custom.css"]

[params.theme]
palette = "base16-catppuccin-frappe"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/zephyrtm"

[[params.socialLinks]]
icon = "fa-brands fa-mastodon"
title = "Mastodon"
url = "https://mastodon.social/@zephyruszt"

[[params.socialLinks]]
icon = "fa-solid fa-square-rss"
title = "RSS"
url = "https://zephyrtm.github.io/index.xml"